import "../app/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Sidebar from "../app/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="flex-ro flex justify-center">
          <div className="w-1/3 sm:">
            <Sidebar />
          </div>
          <div className="w-1/3">{children}</div>
          <div className="w-1/3 sm:hidden">
            <h1>Hello world</h1>
          </div>
        </div>
      </body>
    </html>
  );
}
