import "@/app/globals.css";
import { Navigation } from "./_components/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <div className="mx-auto flex min-h-screen sm:max-w-2xl sm:gap-x-3 sm:px-4">
          <Navigation />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
