import "@/app/globals.css";
import { MainNav } from "@/components/MainNav/page";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className=" flex flex-col items-center ">
          <div className="flex">
            {/* ↓stickyが効かない対策のdiv*/}
            <div>
              <MainNav />
            </div>
            {/* スクロール確認用のh-[1000px] */}
            <main className="h-[1000px] border">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
